### ISSUE TITLE
Does not run when I build it and go to it my browser

### ISSUE THREAD

**Issue by PhilAndrew** [vsavkin/angulardart-sample-app#16]
'HTMLSourceElement.media' is deprecated. This attribute doesn't do anything.
'HTMLVideoElement.webkitDisplayingFullscreen' is deprecated. Please use the 'fullscreenchange' and 'webkitfullscreenchange' events instead.
'HTMLVideoElement.webkitSupportsFullscreen' is deprecated. Its value is true if the video is loaded.
Unsupported operation: Cannot find class for: DynamicMetadataExtractor

STACKTRACE:
Error
    at dart.wrapException (http://localhost:8888/build/web/talk_to_me_main.dart.js:3043:15)
    at dart.reflectClassByName (http://localhost:8888/build/web/talk_to_me_main.dart.js:35819:15)
    at dart.reflectClassByMangledName (http://localhost:8888/build/web/talk_to_me_main.dart.js:35784:14)
    at dart.reflectType (http://localhost:8888/build/web/talk_to_me_main.dart.js:49845:14)
    at DynamicInjector.newInstanceOf$4 (http://localhost:8888/build/web/talk_to_me_main.dart.js:50800:23)
    at TypeProvider.get$4 (http://localhost:8888/build/web/talk_to_me_main.dart.js:50958:23)
    at DynamicInjector.BaseInjector.getInstanceByKey$3 (http://localhost:8888/build/web/talk_to_me_main.dart.js:50666:24)
    at DynamicInjector_newInstanceOf_resolveArgument.call$1 (http://localhost:8888/build/web/talk_to_me_main.dart.js:50832:19)
    at dart.List.static.List_List$generate.H.computeSignature.func (http://localhost:8888/build/web/talk_to_me_main.dart.js:44447:26)
    at DynamicInjector.newInstanceOf$4 (http://localhost:8888/build/web/talk_to_me_main.dart.js:50811:16) js_primitives.dart:25

**Comment by vsavkin** [comment]
Thanks. I'll look into it.
