### ISSUE TITLE
error when run in chrome

### ISSUE THREAD

**Issue by sethladd** [vsavkin/angulardart-sample-app#8]
Here's what I get:

```
NotFoundError: Failed to execute 'appendChild' on 'Node': The new child element is null.

STACKTRACE:
Error: Failed to execute 'appendChild' on 'Node': The new child element is null.
    at HtmlElement.Node.append$1 (http://localhost:8080/talk_to_me.dart.js:34347:23)
    at dart.J.append$1$x (http://localhost:8080/talk_to_me.dart.js:43492:39)
    at NgViewDirective__show__closure.call$1 (http://localhost:8080/talk_to_me.dart.js:14942:16)
    at dart.IterableMixinWorkaround_forEach (http://localhost:8080/talk_to_me.dart.js:17166:9)
    at JSArray.forEach$1.H.computeSignature.func [as forEach$1] (http://localhost:8080/talk_to_me.dart.js:724:16)
    at dart.J.forEach$1$ax (http://localhost:8080/talk_to_me.dart.js:43567:40)
    at NgViewDirective__show_closure0.call$1 (http://localhost:8080/talk_to_me.dart.js:14934:9)
    at _Future._onValue$1 (http://localhost:8080/talk_to_me.dart.js:21172:34)
    at _Future__propagateToListeners_closure0.call$0 (http://localhost:8080/talk_to_me.dart.js:21447:44)
    at _rootRun (http://localhost:8080/talk_to_me.dart.js:20721:16) 
```

When I try to load the app when served from `pub serve`

**Comment by sethladd** [comment]
When I load the URL into Dartium, it works fine.

**Comment by sethladd** [comment]
Also, when I load the app in Canary, it works.

The error is with 32.0.1700.102 apparently.

**Comment by sethladd** [comment]
Fixed with https://github.com/vsavkin/angulardart-sample-app/pull/7
